PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [ 25, 45, 65 ]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 100
  early_stop: 15
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_emb_dim: 24
    tod_emb_dim: 24
    dow_emb_dim: 24
    adaptive_emb_dim: 80
    feed_forward_dim: 256
    cross_feed_forward_dim: 64
    cross_heads: 8
    num_heads: 4
    num_layers: 2
    dropout: 0.1

MANCHESTER:
  num_nodes: 277
  in_steps: 4
  out_steps: 4

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [ 25, 45, 65 ]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 100
  early_stop: 15
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 277
    in_steps: 4
    out_steps: 4
    steps_per_day: 96
    input_dim: 3
    output_dim: 1
    input_emb_dim: 24
    tod_emb_dim: 24
    dow_emb_dim: 24
    adaptive_emb_dim: 80
    feed_forward_dim: 256
    cross_feed_forward_dim: 64
    cross_heads: 4
    num_heads: 4
    num_layers: 2
    dropout: 0.1

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [ 25, 45, 65 ]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 1
  early_stop: 15
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_emb_dim: 24
    tod_emb_dim: 24
    dow_emb_dim: 24
    adaptive_emb_dim: 80
    feed_forward_dim: 256
    cross_feed_forward_dim: 32
    cross_heads: 8
    num_heads: 4
    num_layers: 2
    dropout: 0.1